openapi: 3.0.0
info:
  title: Simple To-Do List API
  description: A basic API for managing a to-do list.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server
paths:
  /todos:
    get:
      summary: Get all to-do items
      description: Returns a list of all to-do items for the user.
      responses:
        '200':
          description: A successful response with a list of to-do items.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Buy groceries"
                    completed:
                      type: boolean
                      example: false
  /todos/{id}:
    get:
      summary: Get a single to-do item
      description: Returns a single to-do item by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A successful response with the requested to-do item.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: "Buy groceries"
                  completed:
                    type: boolean
                    example: false
